### ISSUE TITLE
about questions in the dataset

### ISSUE THREAD

**Issue by haoyuwangwhy** [AlexTMallen/adaptive-retrieval#4]
Hi,

I find a lot of questions in the PopQA such as "What genre is Organisation?" is very vague and almost can not be answered correctly by human. When using Wikipedia to retrieve documents related to the question, I get the following top-10 docs:

**knowledge  0 : Nature and Organisation | Nature And Organisation is the creative musical works of British musician Michael Cashmore. The music of Nature And Organisation is characterized by a mix of acoustic, classical and folk structures met with abrasive electronic instrumentation.
knowledge  1 : Organisation (album) | Organisation is the second album by Orchestral Manoeuvres in the Dark (OMD), released in 1980. " Enola Gay" was the only single taken from the record. Malcolm Holmes had played drums with OMD before, notably on "Julia's Song" which was featured on the band's debut album, and for "Organisation" he was recruited as a full-time member replacing the TEAC tape recorder affectionately named "Winston". " The More I See You" is a cover of a song written by Mack Gordon and Harry Warren in 1945, and popularised by Chris Montez in 1966. The record was remastered and re-released in 2003, with several bonus tracks.
knowledge  2 : Organised Sound | Organised Sound is an international peer-reviewed academic journal which focuses on the rapidly developing methods and issues arising from the use of technology in music today. Published three times a year, it concentrates upon the impact which the application of technology is having upon music in a variety of genres, including sound art, sound sculpture and music ranging from popular idioms to experimental electroacoustic composition. It thus provides a forum for those interested in electroacoustic music studies, its creation and related developments to share the results of their research as they affect musical issues. Whilst an accompanying CD/CD-ROM/DVD is sent to subscribers annually all media content is or will soon also be available online.
knowledge  3 : Organisation (band) | Organisation zur Verwirklichung gemeinsamer Musikkonzepte (German: "Organisation for the Realization of Common Music Concepts"), was an experimental krautrock band, that was the immediate predecessor of the band Kraftwerk. In addition to the founding members of Kraftwerk, Ralf Hütter and Florian Schneider-Esleben, Organisation included Basil Hammoudi, Butch Hauf, and Fred Monicks. The band was assisted by Paul Lorenz, Peter Martini, and Charly Weiss during their career.
knowledge  4 : The Organization (band) | The Organization was a heavy metal band formed in 1991 after the breakup of the thrash metal band Death Angel. The band incorporated elements of metal, funk, and alt rock, releasing two albums in the early 1990s on Metal Blade Records. The band included the original line-up of musicians from Death Angel minus singer Mark Osegueda who left the music business to go to college. The Organization disbanded after bassist Dennis Pepa left the band in 1995.
knowledge  5 : Organization (journal) | Organization is a peer-reviewed academic journal that covers the field of management and organization studies. The editors-in-chief are Craig Prichard (Massey University) and Robyn Thomas (Cardiff Business School). It was established in 1994 and is published by Sage Publications.
knowledge  6 : The Organization (TV Series) | The Organization is a British television drama series, produced by Yorkshire Television for the ITV network in 1972.
knowledge  7 : Organizations (book) | Organizations is a book by James G. March and Herbert A. Simon.
knowledge  8 : Making Music (organisation) | Making Music (formerly the National Federation of Music Societies) is a UK organisation for voluntary music, with around 3,000 member groups. Its members include choirs, orchestras, music promoters, jazz and wind bands, community festivals, and samba groups, among others.
knowledge  9 : Come Organisation | Come Organisation was a record label started by William Bennett in 1979 as a way to release albums by his own band, Come, when he was unable to find a label willing to release them. It is best known for releasing the work of Bennett's subsequent band, Whitehouse.**

We can find Organisation corresponds to multiple different items and the question does not describe the specific item it is related to. Therefore, both model and human can not get a correct answer. Would you like to make the questions in the dataset more clear?

**Comment by AlexTMallen** [comment]
Hi, there will inevitably be some ambiguity in datasets like this. Adding clarifying details inherently trades off against making a controlled comparison between entities, as less popular entities need more clarification. (Further, there is no way to change this now that the dataset has already been released.) The ambiguity is also somewhat realistic to real-world scenarios where users don't add clarifying details, and the most likely interpretation of the query is expected to be used.

If you'd like, you can resolve these ambiguities for your use-case using the wikipedia entity IDs given in the dataset.
