### ISSUE TITLE
code for getting the retrieval results

### ISSUE THREAD

**Issue by ccccccchuang** [AlexTMallen/adaptive-retrieval#5]
Hi, thanks for the nice work! I've been having trouble getting the retrieval results recently. Would you mind sharing the code that got the retrieval  results?

**Comment by AlexTMallen** [comment]
Hi, unfortunately I don't have easy access to that code anymore, but we did not do anything special for our retrieval results beyond what's mentioned in the paper, using off-the-shelf BM25 and Contriever. Thanks for your interest!

**Comment by Chengkai-Huang** [comment]
Could you inform whether any Python library is used for BM25 retrieval? It seems very slow to search the entire Wiki_DPR text for each entity. Or any techniques to speed it up?

**Comment by ccccccchuang** [comment]
@Chengkai-Huang Yeah, I also because of the slow retrieval, with a batch of 1024 sentence matrix operation may be a bit faster, but the overall speed is still very slow.

**Comment by AlexTMallen** [comment]
We used https://pypi.org/project/rank-bm25/ for BM25

**Comment by BUGLI27** [comment]
@Chengkai-Huang Same Question, it takes 55.31s to retrieval 1 question, and it takes 200 hours to complete the BM25 retrieval of the dataset.
@AlexTMallen Hi, could you share the BM25/contriever result file of the popQA dataset for download?

**Comment by AlexTMallen** [comment]
Here are the retrieved docs for EQ and PopQA!
[EntityQuestions_bm25_500_retrieved_docs.json](https://github.com/AlexTMallen/adaptive-retrieval/files/14103781/EntityQuestions_bm25_500_retrieved_docs.json)
[PopQA_BM25.jsonl.zip](https://github.com/AlexTMallen/adaptive-retrieval/files/14104572/PopQA_BM25.jsonl.zip)

**Comment by BUGLI27** [comment]
> Here are the retrieved docs for EQ and PopQA! [EntityQuestions_bm25_500_retrieved_docs.json](https://github.com/AlexTMallen/adaptive-retrieval/files/14103781/EntityQuestions_bm25_500_retrieved_docs.json) [PopQA_BM25.jsonl.zip](https://github.com/AlexTMallen/adaptive-retrieval/files/14104572/PopQA_BM25.jsonl.zip)

Thanks, that helps a lot!

**Comment by yfqiu98** [comment]
Hello. Many thanks for sharing BM25's retrieval results, is there any possibility for sharing contriver as well? I might miss it, but I think the google drive's sharing link for retriever results just points to an empty folder.

**Comment by AlexTMallen** [comment]
Unfortunately I don't believe I have access to those anymore.

**Comment by wizard1203** [comment]
> EntityQuestions_bm25_500_retrieved_docs.json

Great! Another question, If I do not hope to test the retriver, could I directly use the s_uri and o_uri as the retrived results for testing? It might be an oracle results of the retriving, if I understand correctly
