### ISSUE TITLE
Wikidata IDs?

### ISSUE THREAD

**Issue by spaidataiga** [AlexTMallen/adaptive-retrieval#7]
Hi, thank you for this interesting paper! I was looking into using the PopularQA dataset, to which you have also included the Wikidata entity IDs. However, when checking this, it seems that the IDs provided per question do not seem to align with the actual Wikidata IDs for the named entity? 

For example, in question id 4222362, you provide the following: For subject George Rankin, you provide the wikidata ID 1850297. However, this ID corresponds to a species of fish: Diogenichthys atlanticus, and the Wikidata entity ID for George Rankin is Q5543720. Similarly, the ID provided for the property `occupation' is 22, which corresponds to 'father of' in Wikidata properties. This continues for all examples I have checked.

Do these numbers not refer to wikidata IDs, or am I missing something?

**Comment by AlexTMallen** [comment]
Hi! You're correct that they don't refer to wikidata IDs - the wikidata IDs can be inferred from the `s_uri` and `o_uri` columns.
