### ISSUE TITLE
Questions about PopQA’s entity source and sampling methods

### ISSUE THREAD

**Issue by yiming-zh** [AlexTMallen/adaptive-retrieval#8]
Hello, I read your article and found it very interesting. I'm currently doing research around your work but having trouble.

I have the following two questions:
* Which wiki knowledge source is the current knowledge triple of popQA extracted from? 
    This issue does not seem to be explained in the article.
* Could you please provide the code for knowledge triple extraction?
     The introduction to extraction in Appendix A is confusing. 
     > ... we include the knowledge triple if and only if f > exp(8R − 6), where R ∼ U (0, 1) is a unit uniform pseudo-random number and f is the exact match term frequency of the subject entity’s aliases in an 800 MB random sample of C4. ...

    Some mentions, such as C4, and 800MB, have no explanation.

**Comment by AlexTMallen** [comment]
Hi! We forgot to include a citation there for the C4 dataset - can be found at [this link](https://huggingface.co/datasets/allenai/c4) - please use the english subset. The first 800 mb random sample is the one we used.

Here is the [code](https://gist.github.com/AlexTMallen/f7e821449ff0f2360aff4bac7a8a5256) for dataset creation. `m2rqa.db` is from the [ROMQA](https://arxiv.org/abs/2210.14353) dataset.
